language: node_js

before_script:
  - sudo add-apt-repository -y ppa:terry.guo/gcc-arm-embedded
  - sudo apt-get -y update
  - sudo apt-get -y install qemu qemu-kvm-extras gcc-arm-none-eabi luajit
  - sudo ln -s /usr/bin/luajit-2.0.0-beta9 /usr/bin/luajit
  - npm install -g tinytap

script:
  - make test
